spring:
  application:
    name: CAMS-GP-Server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cams_gp?serverTimezone=Asia/Shanghai
    username: root
    password: 1505011271

  mvc:
    converters:
      preferred-json-mapper: gson

  gson:
    date-format: yyyy/MM/dd HH:mm:ss


server:
  port: 8081

