
###
# @no-cookie-jar
POST http://localhost:8081/public/secret/log/in
Content-Type: application/json

{
  "username": "10001",
  "password": "123456"
}



###
# @no-cookie-jar
GET http://localhost:8081/private/person/info/search/me
Content-Type: application/x-www-form-urlencoded
session: a6cd8154-22dd-4e2a-8e39-bb77f1b5303c


